### ISSUE TITLE
perlin1DValueForPoint always returns 0.

### ISSUE THREAD

**Issue by jflo** [westongpt/PerlinNoiseKit#1]
PerlinNoise *perlin = [[PerlinNoise alloc]initWithSeed:25];
    for (int x=0; x<mapWidth; x++) {
        float y = [perlin perlin1DValueForPoint:x];
        NSLog(@"for f(%d) = %f",x, [perlin perlin1DValueForPoint:x]);
    }

This isn't caught by your unit test either.

**Comment by westongpt** [comment]
yea, this code is a little wonky, I need to get it updated... I will take a look over the weekend. Thanks!

**Comment by jasonmcdermott** [comment]
Any update on this issue?  I'd love to use perlin1D but it's only returning 0

**Comment by westongpt** [comment]
I am sorry, I have been busy lately, and have completely neglected this work. I swear I will try to get this fixed soon.

**Comment by westongpt** [comment]
ok, I am going to work on this a bit today, the code is ~2 years old and I need to get it updated.

**Comment by westongpt** [comment]
I fixed the perlin 1 and 2 d functions, and wrote some tests to keep them in check. let me know if you have issues.
